### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by gavryushkin** [bioDS/rnni_polynomial_paper#19]
Are we ready to replace "Specifically, our algorithm scales to trees with thousands of leaves (and likely hundreds
of thousands if implemented efficiently)." with something more definitive? @lenacoll how is your C code doing?

**Comment by gavryushkin** [comment]
ping

**Comment by gavryushkin** [comment]
?

**Comment by lenacoll** [comment]
I somehow always forget about this. But I'm working on it now (still need to fix my code, it doesn't like big trees (yet)

**Comment by lenacoll** [comment]
update: an example on 100,000 leaves took me about 5 hours on my laptop (for computing the distance, not the actual path).

**Comment by gavryushkin** [comment]
Assuming the accepted version is tagged as a release, please make the necessary change.
